name: War Dragons Strategy
favicon: null
layout_spectrum: 0.673573553096503
typography_spectrum: 0.14967582165263593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17098013288341463
  lightness: 0.26301107089966536
  saturation: 0.8556025945581496
  rhythmicContrast: 0.2843786331359297
purpose: []
